# Generated by Django 5.2.10 on 2026-02-02 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_equipment_count", models.IntegerField()),
                ("avg_flowrate", models.FloatField()),
                ("avg_pressure", models.FloatField()),
                ("avg_temperature", models.FloatField()),
                ("equipment_type_distribution", models.JSONField()),
                ("file_path", models.CharField(max_length=500)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-upload_timestamp"],
            },
        ),
    ]
